version: 2
jobs:
  build:
      docker:
        - image: node:7
      branches:
        - only:
          - v2
      steps:
        - run:
           name: Build module
           command: npm run build
        - run:
           name: Build docs
           command: node scripts/update_docs.js
        - deploy:
           name: Deploy docs to gh-pages
           command: bash ./scripts/update_docs.sh
